version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    build: ./db
    ports:
      - "27017:27017"
